let myMusic={},otherMusic={},searchPage=1,lastQuery='',selectedMusic=null;
requireAuth(async u=>{document.getElementById('otherOnlyTitle').textContent=`Ascoltati da ${labelFor(otherUser(u))} ma non da te`;document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')searchMusic(true)});await refreshLibraries()});
async function spotify(params){const r=await fetch('/.netlify/functions/spotify?'+new URLSearchParams(params));const d=await r.json();if(!r.ok)throw new Error(d.error||'Errore Spotify');return d}
function imageOf(x){return x.images?.[0]?.url||x.album?.images?.[0]?.url||''}function titleOf(x){return x.name||'Senza titolo'}function artistOf(x){return x.artists?.map(a=>a.name).join(', ')||''}
async function searchMusic(reset){const q=document.getElementById('searchInput').value.trim();if(!q)return;if(reset){lastQuery=q;searchPage=1;document.getElementById('searchResults').innerHTML='<div class="loading">Ricerca…</div>'}else searchPage++;try{const d=await spotify({action:'search',q:lastQuery,page:searchPage});const items=[];(d.tracks?.items||[]).forEach(x=>items.push({...x,_type:'track'}));(d.albums?.items||[]).forEach(x=>items.push({...x,_type:'album'}));(d.artists?.items||[]).forEach(x=>items.push({...x,_type:'artist'}));const box=document.getElementById('searchResults');if(reset)box.innerHTML='';box.insertAdjacentHTML('beforeend',items.map(searchCard).join('')||'<div class="empty">Nessun risultato.</div>');document.getElementById('searchSection').classList.remove('hidden');document.getElementById('searchCount').textContent=`${items.length} risultati in questa pagina`;document.getElementById('moreSearch').style.display=items.length?'inline-block':'none'}catch(e){setError(e.message)}}
function searchCard(x){const im=imageOf(x),type=x._type||x.type;return `<article class="poster-card" onclick="openDetail('${type}','${x.id}')">${im?`<img loading="lazy" src="${im}" alt="">`:`<div class="poster-fallback">${escapeHtml(x.name)}</div>`}<div class="card-info"><div class="card-title">${escapeHtml(x.name)}</div><div class="card-meta">${escapeHtml(type==='artist'?'Artista':type==='album'?'Album · '+artistOf(x):'Brano · '+artistOf(x))}</div></div></article>`}
function libraryCard(x,owner=currentUsername){const m=x.metadata||{};return `<article class="poster-card" onclick="openDetail('${m.type}','${m.spotifyId}')">${m.imageUrl?`<img loading="lazy" src="${m.imageUrl}" alt="">`:`<div class="poster-fallback">${escapeHtml(m.title||'Musica')}</div>`}<span class="author-dot ${owner}"></span><div class="card-info"><div class="card-title">${escapeHtml(m.title||'Musica')}</div><div class="card-meta">${escapeHtml(m.subtitle||statusText(x))}</div></div></article>`}
function statusText(x){return x.status==='listened'?'Ascoltato':x.status==='listening'?'In ascolto':'Da ascoltare'}
async function refreshLibraries(){[myMusic,otherMusic]=await Promise.all([readLibrary('music',currentUsername),readLibrary('music',otherUser(currentUsername))]);renderSections()}
function renderSections(){const mine=Object.values(myMusic),other=Object.values(otherMusic);renderRail('listeningRail',mine.filter(x=>x.status==='listening'));renderRail('wantRail',mine.filter(x=>x.status==='want'));renderRail('doneRail',mine.filter(x=>x.status==='listened'));renderRail('favoritesRail',mine.filter(x=>x.favorite));renderRail('otherOnlyRail',other.filter(x=>x.status==='listened'&&myMusic[x.id]?.status!=='listened'),otherUser(currentUsername));renderRail('bothRail',mine.filter(x=>x.status==='listened'&&otherMusic[x.id]?.status==='listened'))}
function renderRail(id,items,owner=currentUsername){document.getElementById(id).innerHTML=items.length?items.map(x=>libraryCard(x,owner)).join(''):'<div class="empty">Ancora niente qui.</div>'}
async function openDetail(type,id){document.getElementById('detailModal').classList.add('open');document.getElementById('modalContent').innerHTML='<div class="loading">Caricamento dettagli…</div>';try{selectedMusic=normalize(type,await spotify({action:'details',type,id}));renderDetail()}catch(e){document.getElementById('modalContent').innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`}}
function normalize(type,d){const artists=d.artists?.map(a=>a.name)||[];const album=type==='track'?d.album:null;return{type,spotifyId:d.id,title:d.name||'Senza titolo',subtitle:type==='artist'?'Artista':type==='album'?artists.join(', '):artists.join(', '),imageUrl:imageOf(d),externalUrl:d.external_urls?.spotify||'',genres:d.genres||[],popularity:d.popularity??null,followers:d.followers?.total??null,releaseDate:d.release_date||album?.release_date||'',totalTracks:d.total_tracks||album?.total_tracks||null,durationMs:d.duration_ms||null,explicit:d.explicit??null,albumName:album?.name||'',trackNumber:d.track_number||null,discNumber:d.disc_number||null,artists,recordLabel:d.label||'',copyrights:(d.copyrights||[]).map(x=>x.text),albumType:d.album_type||'',uri:d.uri||''}}
function renderDetail(){const m=selectedMusic,k=m.type+'_'+m.spotifyId,s=myMusic[k]||{};document.getElementById('modalHero').style.backgroundImage=m.imageUrl?`url('${m.imageUrl}')`:'';const mins=m.durationMs?Math.floor(m.durationMs/60000)+':'+String(Math.floor((m.durationMs%60000)/1000)).padStart(2,'0'):'';document.getElementById('modalContent').innerHTML=`<h2>${escapeHtml(m.title)}</h2><div class="chips"><span class="chip">${escapeHtml(m.type==='track'?'Brano':m.type==='album'?'Album':'Artista')}</span>${m.releaseDate?`<span class="chip">${escapeHtml(m.releaseDate)}</span>`:''}${mins?`<span class="chip">${mins}</span>`:''}${m.genres.slice(0,6).map(g=>`<span class="chip">${escapeHtml(g)}</span>`).join('')}</div><div class="metadata"><div><b>Artista/i:</b> ${escapeHtml(m.artists.join(', ')||m.subtitle||'—')}</div><div><b>Album:</b> ${escapeHtml(m.albumName||'—')}</div><div><b>Tracce:</b> ${m.totalTracks??'—'}</div><div><b>Etichetta:</b> ${escapeHtml(m.recordLabel||'—')}</div><div><b>Popolarità:</b> ${m.popularity??'—'}</div><div><b>Follower:</b> ${m.followers?.toLocaleString('it-IT')||'—'}</div><div><b>Esplicito:</b> ${m.explicit===null?'—':m.explicit?'Sì':'No'}</div><div><b>Spotify:</b> ${m.externalUrl?`<a href="${m.externalUrl}" target="_blank" rel="noopener">Apri su Spotify</a>`:'—'}</div></div><div class="personal-box"><h3>La tua scheda</h3><div class="form-grid"><div class="field"><label>Stato</label><select id="detailStatus"><option value="want" ${s.status==='want'?'selected':''}>Vuoi ascoltare</option><option value="listening" ${s.status==='listening'?'selected':''}>Stai ascoltando</option><option value="listened" ${s.status==='listened'?'selected':''}>Ascoltato</option></select></div><div class="field favorite-toggle"><label><input id="detailFavorite" type="checkbox" ${s.favorite?'checked':''}> Preferito</label></div><div class="field"><label>Il tuo voto (0-10)</label><input id="detailRating" type="number" min="0" max="10" step="0.5" value="${s.userRating??''}"></div><div class="field full"><label>Note personali</label><textarea id="detailNotes">${escapeHtml(s.notes||'')}</textarea></div></div><div class="save-row"><button class="save-btn" onclick="saveCurrentMusic()">Salva / aggiorna</button>${s.id?`<button class="danger-btn" onclick="removeCurrentMusic()">Rimuovi</button>`:''}</div></div>`}
async function saveCurrentMusic(){const m=selectedMusic,k=m.type+'_'+m.spotifyId;await saveLibraryItem('music',k,{spotifyId:m.spotifyId,status:document.getElementById('detailStatus').value,favorite:document.getElementById('detailFavorite').checked,userRating:Number(document.getElementById('detailRating').value)||null,notes:document.getElementById('detailNotes').value.trim(),metadata:m,createdAt:myMusic[k]?.createdAt||firebase.firestore.FieldValue.serverTimestamp()});showToast('Salvato');await refreshLibraries();renderDetail()}
async function removeCurrentMusic(){const k=selectedMusic.type+'_'+selectedMusic.spotifyId;if(!confirm('Rimuovere questo elemento?'))return;await deleteLibraryItem('music',k);await refreshLibraries();showToast('Rimosso');closeDetail()}
function closeDetail(){document.getElementById('detailModal').classList.remove('open');selectedMusic=null}
