let myGames={},otherGames={},searchPage=1,lastQuery='',selectedGame=null;
requireAuth(async u=>{document.getElementById('otherOnlyTitle').textContent=`Giocati da ${labelFor(otherUser(u))} ma non da te`;document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')searchGames(true)});await refreshLibraries()});
async function igdb(params){const r=await fetch('/.netlify/functions/igdb?'+new URLSearchParams(params));const d=await r.json();if(!r.ok)throw new Error(d.error||'Errore IGDB');return d}
function imgUrl(u=''){if(!u)return'';return ('https:'+u).replace('t_thumb','t_cover_big').replace('https:https:','https:')}
function year(ts){return ts?new Date(ts*1000).getFullYear():''}
async function searchGames(reset){const q=document.getElementById('searchInput').value.trim();if(!q)return;if(reset){lastQuery=q;searchPage=1;document.getElementById('searchResults').innerHTML='<div class="loading">Ricerca…</div>'}else searchPage++;try{const d=await igdb({action:'search',q:lastQuery,page:searchPage});const items=d.results||[],box=document.getElementById('searchResults');if(reset)box.innerHTML='';box.insertAdjacentHTML('beforeend',items.map(searchCard).join('')||'<div class="empty">Nessun risultato.</div>');document.getElementById('searchSection').classList.remove('hidden');document.getElementById('searchCount').textContent=`Pagina ${searchPage} · ${items.length} risultati`;document.getElementById('moreSearch').style.display=items.length===20?'inline-block':'none'}catch(e){setError(e.message)}}
function searchCard(x){const im=imgUrl(x.cover?.url);return `<article class="poster-card" onclick="openDetail(${Number(x.id)})">${im?`<img loading="lazy" src="${im}" alt="">`:`<div class="poster-fallback">${escapeHtml(x.name)}</div>`}<div class="card-info"><div class="card-title">${escapeHtml(x.name)}</div><div class="card-meta">${year(x.first_release_date)||'—'}${x.platforms?.length?' · '+escapeHtml(x.platforms.slice(0,2).map(p=>p.name).join(', ')):''}</div></div></article>`}
function libraryCard(x,owner=currentUsername){const m=x.metadata||{},im=m.coverUrl||'';return `<article class="poster-card" onclick="openDetail(${Number(x.igdbId)})">${im?`<img loading="lazy" src="${im}" alt="">`:`<div class="poster-fallback">${escapeHtml(m.title||'Gioco')}</div>`}<span class="author-dot ${owner}"></span><div class="card-info"><div class="card-title">${escapeHtml(m.title||'Gioco')}</div><div class="card-meta">${escapeHtml(progressText(x))}</div>${progressPercent(x)>0?`<div class="progress-line"><i style="width:${progressPercent(x)}%"></i></div>`:''}</div></article>`}
function progressText(x){if(x.status==='completed')return'Completato';if(x.status==='playing')return `${Number(x.progressPercent||0)}% · ${Number(x.hoursPlayed||0)} h`;return x.metadata?.year||''}
function progressPercent(x){return x.status==='completed'?100:Math.max(0,Math.min(100,Number(x.progressPercent||0)))}
async function refreshLibraries(){[myGames,otherGames]=await Promise.all([readLibrary('games',currentUsername),readLibrary('games',otherUser(currentUsername))]);renderSections()}
function renderSections(){const mine=Object.values(myGames),other=Object.values(otherGames);renderRail('playingRail',mine.filter(x=>x.status==='playing'));renderRail('wantRail',mine.filter(x=>x.status==='want'));renderRail('doneRail',mine.filter(x=>x.status==='completed'));renderRail('favoritesRail',mine.filter(x=>x.favorite));renderRail('otherOnlyRail',other.filter(x=>x.status==='completed'&&myGames[x.id]?.status!=='completed'),otherUser(currentUsername));renderRail('bothRail',mine.filter(x=>x.status==='completed'&&otherGames[x.id]?.status==='completed'))}
function renderRail(id,items,owner=currentUsername){const e=document.getElementById(id);e.innerHTML=items.length?items.map(x=>libraryCard(x,owner)).join(''):'<div class="empty">Ancora niente qui.</div>'}
async function openDetail(id){document.getElementById('detailModal').classList.add('open');document.getElementById('modalContent').innerHTML='<div class="loading">Caricamento dettagli…</div>';try{const d=await igdb({action:'details',id});selectedGame=normalize(d);renderDetail()}catch(e){document.getElementById('modalContent').innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`}}
function normalize(d){const companies=(d.involved_companies||[]);return{igdbId:d.id,title:d.name||'Senza titolo',summary:d.summary||d.storyline||'',coverUrl:imgUrl(d.cover?.url),year:year(d.first_release_date),releaseDate:d.first_release_date?new Date(d.first_release_date*1000).toLocaleDateString('it-IT'):'',genres:(d.genres||[]).map(x=>x.name),themes:(d.themes||[]).map(x=>x.name),platforms:(d.platforms||[]).map(x=>x.name),gameModes:(d.game_modes||[]).map(x=>x.name),perspectives:(d.player_perspectives||[]).map(x=>x.name),developers:companies.filter(x=>x.developer).map(x=>x.company?.name).filter(Boolean),publishers:companies.filter(x=>x.publisher).map(x=>x.company?.name).filter(Boolean),franchises:(d.franchises||[]).map(x=>x.name),collection:d.collection?.name||'',rating:d.total_rating||d.rating||0,ratingCount:d.total_rating_count||d.rating_count||0,hypes:d.hypes||0,follows:d.follows||0,websites:(d.websites||[]).map(x=>x.url),screenshots:(d.screenshots||[]).map(x=>imgUrl(x.url).replace('t_cover_big','t_screenshot_big')),videos:(d.videos||[]).map(x=>x.video_id),dlcs:(d.dlcs||[]).map(x=>x.name),expansions:(d.expansions||[]).map(x=>x.name),remakes:(d.remakes||[]).map(x=>x.name),remasters:(d.remasters||[]).map(x=>x.name),similar:(d.similar_games||[]).map(x=>x.name),parent:d.parent_game?.name||'',releaseDates:(d.release_dates||[]).map(x=>[x.human,x.platform?.name].filter(Boolean).join(' · ')).filter(Boolean)}}
function renderDetail(){const m=selectedGame,k='game_'+m.igdbId,s=myGames[k]||{};document.getElementById('modalHero').style.backgroundImage=m.screenshots[0]?`url('${m.screenshots[0]}')`:m.coverUrl?`url('${m.coverUrl}')`:'';document.getElementById('modalContent').innerHTML=`<h2>${escapeHtml(m.title)}</h2><div class="chips">${m.year?`<span class="chip">${m.year}</span>`:''}${m.genres.map(g=>`<span class="chip">${escapeHtml(g)}</span>`).join('')}${m.platforms.slice(0,5).map(g=>`<span class="chip">${escapeHtml(g)}</span>`).join('')}</div><p class="synopsis">${escapeHtml(m.summary||'Nessuna descrizione disponibile.')}</p><div class="metadata"><div><b>Uscita:</b> ${escapeHtml(m.releaseDate||'—')}</div><div><b>Valutazione IGDB:</b> ${m.rating?m.rating.toFixed(1)+'/100':'—'} (${m.ratingCount||0})</div><div><b>Sviluppatori:</b> ${escapeHtml(m.developers.join(', ')||'—')}</div><div><b>Publisher:</b> ${escapeHtml(m.publishers.join(', ')||'—')}</div><div><b>Piattaforme:</b> ${escapeHtml(m.platforms.join(', ')||'—')}</div><div><b>Modalità:</b> ${escapeHtml(m.gameModes.join(', ')||'—')}</div><div><b>Temi:</b> ${escapeHtml(m.themes.join(', ')||'—')}</div><div><b>Prospettiva:</b> ${escapeHtml(m.perspectives.join(', ')||'—')}</div><div><b>Franchise:</b> ${escapeHtml(m.franchises.join(', ')||m.collection||'—')}</div><div><b>DLC/Espansioni:</b> ${escapeHtml([...m.dlcs,...m.expansions].join(', ')||'—')}</div></div><div class="personal-box"><h3>La tua scheda</h3><div class="form-grid"><div class="field"><label>Stato</label><select id="detailStatus"><option value="want" ${s.status==='want'?'selected':''}>Vuoi giocare</option><option value="playing" ${s.status==='playing'?'selected':''}>Stai giocando</option><option value="completed" ${s.status==='completed'?'selected':''}>Completato</option></select></div><div class="field favorite-toggle"><label><input id="detailFavorite" type="checkbox" ${s.favorite?'checked':''}> Preferito</label></div><div class="field"><label>Progresso %</label><input id="progressPercent" type="number" min="0" max="100" value="${Number(s.progressPercent||0)}"></div><div class="field"><label>Ore giocate</label><input id="hoursPlayed" type="number" min="0" step="0.5" value="${Number(s.hoursPlayed||0)}"></div><div class="field full"><label>Punto raggiunto / missione / capitolo</label><input id="progressText" value="${escapeHtml(s.progressText||'')}"></div><div class="field"><label>Il tuo voto (0-10)</label><input id="detailRating" type="number" min="0" max="10" step="0.5" value="${s.userRating??''}"></div><div class="field full"><label>Note personali</label><textarea id="detailNotes">${escapeHtml(s.notes||'')}</textarea></div></div><div class="save-row"><button class="save-btn" onclick="saveCurrentGame()">Salva / aggiorna</button>${s.id?`<button class="danger-btn" onclick="removeCurrentGame()">Rimuovi</button>`:''}</div></div>`}
async function saveCurrentGame(){const m=selectedGame,k='game_'+m.igdbId;await saveLibraryItem('games',k,{igdbId:m.igdbId,status:document.getElementById('detailStatus').value,favorite:document.getElementById('detailFavorite').checked,progressPercent:Number(document.getElementById('progressPercent').value)||0,hoursPlayed:Number(document.getElementById('hoursPlayed').value)||0,progressText:document.getElementById('progressText').value.trim(),userRating:Number(document.getElementById('detailRating').value)||null,notes:document.getElementById('detailNotes').value.trim(),metadata:m,createdAt:myGames[k]?.createdAt||firebase.firestore.FieldValue.serverTimestamp()});showToast('Salvato');await refreshLibraries();renderDetail()}
async function removeCurrentGame(){const k='game_'+selectedGame.igdbId;if(!confirm('Rimuovere questo gioco?'))return;await deleteLibraryItem('games',k);await refreshLibraries();showToast('Rimosso');closeDetail()}
function closeDetail(){document.getElementById('detailModal').classList.remove('open');selectedGame=null}
